export const accessManagerABI = [
  "constructor()",
  "error AccessManagerAlreadyScheduled(bytes32 operationId)",
  "error AccessManagerBadConfirmation()",
  "error AccessManagerExpired(bytes32 operationId)",
  "error AccessManagerInvalidInitialAdmin(address initialAdmin)",
  "error AccessManagerLockedRole(uint64 roleId)",
  "error AccessManagerNotReady(bytes32 operationId)",
  "error AccessManagerNotScheduled(bytes32 operationId)",
  "error AccessManagerUnauthorizedAccount(address msgsender, uint64 roleId)",
  "error AccessManagerUnauthorizedCall(address caller, address target, bytes4 selector)",
  "error AccessManagerUnauthorizedCancel(address msgsender, address caller, address target, bytes4 selector)",
  "error AccessManagerUnauthorizedConsume(address target)",
  "error AddressEmptyCode(address target)",
  "error FailedCall()",
  "error InsufficientBalance(uint256 balance, uint256 needed)",
  "error SafeCastOverflowedUintDowncast(uint8 bits, uint256 value)",
  "event OperationCanceled(bytes32 indexed operationId, uint32 indexed nonce)",
  "event OperationExecuted(bytes32 indexed operationId, uint32 indexed nonce)",
  "event OperationScheduled(bytes32 indexed operationId, uint32 indexed nonce, uint48 schedule, address caller, address target, bytes data)",
  "event RoleAdminChanged(uint64 indexed roleId, uint64 indexed admin)",
  "event RoleGrantDelayChanged(uint64 indexed roleId, uint32 delay, uint48 since)",
  "event RoleGranted(uint64 indexed roleId, address indexed account, uint32 delay, uint48 since, bool newMember)",
  "event RoleGuardianChanged(uint64 indexed roleId, uint64 indexed guardian)",
  "event RoleLabel(uint64 indexed roleId, string label)",
  "event RoleRevoked(uint64 indexed roleId, address indexed account)",
  "event TargetAdminDelayUpdated(address indexed target, uint32 delay, uint48 since)",
  "event TargetClosed(address indexed target, bool closed)",
  "event TargetFunctionRoleUpdated(address indexed target, bytes4 selector, uint64 indexed roleId)",
  "function ADMIN_ROLE() view returns (uint64)",
  "function PUBLIC_ROLE() view returns (uint64)",
  "function canCall(address caller, address target, bytes4 selector) view returns (bool immediate, uint32 delay)",
  "function cancel(address caller, address target, bytes data) returns (uint32)",
  "function consumeScheduledOp(address caller, bytes data)",
  "function execute(address target, bytes data) payable returns (uint32)",
  "function expiration() view returns (uint32)",
  "function getAccess(uint64 roleId, address account) view returns (uint48 since, uint32 currentDelay, uint32 pendingDelay, uint48 effect)",
  "function getAllRoles() view returns (uint64[])",
  "function getNonce(bytes32 id) view returns (uint32)",
  "function getRoleAdmin(uint64 roleId) view returns (uint64)",
  "function getRoleByIndex(uint256 index) view returns (uint64)",
  "function getRoleCount() view returns (uint256)",
  "function getRoleGrantDelay(uint64 roleId) view returns (uint32)",
  "function getRoleGuardian(uint64 roleId) view returns (uint64)",
  "function getRoleMember(uint64 roleId, uint256 index) view returns (address)",
  "function getRoleMemberCount(uint64 roleId) view returns (uint256)",
  "function getRoleMembers(uint64 roleId) view returns (address[])",
  "function getSchedule(bytes32 id) view returns (uint48)",
  "function getTargetAdminDelay(address target) view returns (uint32)",
  "function getTargetFunctionRole(address target, bytes4 selector) view returns (uint64)",
  "function getTargetFunctionRoles(address target, bytes4[] selectors) view returns ((bytes4 selector, uint64 roleId)[] roleIds)",
  "function grantRole(uint64 roleId, address account, uint32 executionDelay)",
  "function hasRole(uint64 roleId, address account) view returns (bool isMember, uint32 executionDelay)",
  "function hashOperation(address caller, address target, bytes data) view returns (bytes32)",
  "function isTargetClosed(address target) view returns (bool)",
  "function labelRole(uint64 roleId, string label)",
  "function minSetback() view returns (uint32)",
  "function multicall(bytes[] data) returns (bytes[] results)",
  "function renounceRole(uint64 roleId, address callerConfirmation)",
  "function revokeRole(uint64 roleId, address account)",
  "function schedule(address target, bytes data, uint48 when) returns (bytes32 operationId, uint32 nonce)",
  "function setGrantDelay(uint64 roleId, uint32 newDelay)",
  "function setRoleAdmin(uint64 roleId, uint64 admin)",
  "function setRoleGuardian(uint64 roleId, uint64 guardian)",
  "function setTargetAdminDelay(address target, uint32 newDelay)",
  "function setTargetClosed(address target, bool closed)",
  "function setTargetFunctionRole(address target, bytes4[] selectors, uint64 roleId)",
  "function updateAuthority(address target, address newAuthority)"
];